### ISSUE TITLE
PhD institution for sag4012 has changed in ASMS to "Sree Chitra Tirunal Institute for Medical Sciences and Technology" but the old, incorrect affiliation is still in VIVO

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Connect#24]
![image](https://user-images.githubusercontent.com/3651640/106797529-bb2ed400-662a-11eb-8ff1-752fd82bd93c.png)

![image](https://user-images.githubusercontent.com/3651640/106797354-799e2900-662a-11eb-9559-c90515d0847c.png)

![image](https://user-images.githubusercontent.com/3651640/106797452-9cc8d880-662a-11eb-8936-c91948ae6ca8.png)

**Comment by sarbajitdutta** [comment]
The application already accounts for change of institution. This was not working since mssql database connection pool was broken. has been fixed since.
