### ISSUE TITLE
anr3001 should have zero publications in VIVO but has two

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Connect#26]
These were accepted at one time but have since been rejected.

<img width="1153" alt="Screen Shot 2021-03-01 at 11 46 18 AM" src="https://user-images.githubusercontent.com/3651640/109529480-c89d7980-7a83-11eb-9621-05a9ef2a8639.png">

**Comment by sarbajitdutta** [comment]
This is a bug when ReCiter has n number of publications and VIVO imported them and then all publications were rejected from ReCiter then the VIVO publications were not deleted. 
If some publications are rejected then it accounts for that change but not all publications are rejected.

**Comment by sarbajitdutta** [comment]
This is fixed - https://github.com/wcmc-its/ReCiter-Connect/commit/76b482060da3e36d1be71f5f6a0300e50b41d9b5
