### ISSUE TITLE
Publication still in VIVO after rejecting it

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Connect#28]
Pmid = 32961610 has been rejected for cwid = dib2020 last week, but article still remains in VIVO.

<img width="879" alt="Screen Shot 2021-03-22 at 9 02 07 AM" src="https://user-images.githubusercontent.com/3651640/111993749-5b628e80-8aed-11eb-803e-613686c060bb.png">
<img width="1099" alt="Screen Shot 2021-03-22 at 9 01 51 AM" src="https://user-images.githubusercontent.com/3651640/111993753-5bfb2500-8aed-11eb-94ba-68b3f8d7ba87.png">

**Comment by sarbajitdutta** [comment]
@paulalbert1 This is fixed.
