### ISSUE TITLE
erp2001 listed on a grant but that role has been removed from InfoEd

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Connect#29]
Please remove erp2001 entirely from this grant. The data in InfoEd must have changed.
https://vivo.weill.cornell.edu/display/grant-0000037259

Here's InfoEd production for erp2001:
<img width="948" alt="Screen Shot 2021-04-23 at 3 39 51 PM" src="https://user-images.githubusercontent.com/3651640/115921944-3645a080-a44a-11eb-8ce8-eac3b2eb8387.png">

Yet, this faculty is list on the grant.
<img width="979" alt="Screen Shot 2021-04-23 at 3 40 41 PM" src="https://user-images.githubusercontent.com/3651640/115921981-46f61680-a44a-11eb-8bd0-2aaac9988fea.png">

**Comment by sarbajitdutta** [comment]
Fixed!
