### ISSUE TITLE
Appointment for kad9090 not imported

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Connect#31]
![image002](https://user-images.githubusercontent.com/3651640/118282988-dcf6ed00-b49c-11eb-8b80-7155eec2bca4.png)
<img width="1099" alt="Screen Shot 2021-05-14 at 10 11 36 AM" src="https://user-images.githubusercontent.com/3651640/118282998-dec0b080-b49c-11eb-8ec9-7bfea85abb73.png">

**Comment by sarbajitdutta** [comment]
This has been fixed.
