### ISSUE TITLE
Change publication type for 31460973

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Connect#32]
The type for this publication has been changed from "Conference Paper" to "Academic Article" in ReCiter itself, but this is not reflected in VIVO:
https://vivo.weill.cornell.edu/display/pubid31460973

Please update.

<img width="425" alt="Screen Shot 2021-05-20 at 12 36 56 PM" src="https://user-images.githubusercontent.com/3651640/119016707-4167ef80-b968-11eb-96ff-0d26362a277b.png">

<img width="868" alt="Screen Shot 2021-05-20 at 12 38 22 PM" src="https://user-images.githubusercontent.com/3651640/119016738-49279400-b968-11eb-80fa-9cdff62ba0a1.png">

**Comment by sarbajitdutta** [comment]
Looking into it

**Comment by sarbajitdutta** [comment]
Fixed - 2e96a0e972a78b378d577544c12ba6ab04b12614
