### ISSUE TITLE
Grant should be removed from VIVO

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-Connect#33]
This grant should be removed from VIVO because the "Confidential" flag = Y in InfoEd.
https://vivo.weill.cornell.edu/display/grant-0000043198

Please make sure that the code accounts for cases where the flag is changed upstream from N to Y. Note that this record returns as a null when our code is executed against InfoEd. 

Thanks!

<img width="1038" alt="Screen Shot 2021-06-24 at 3 52 46 PM" src="https://user-images.githubusercontent.com/3651640/123324049-5ce48e00-d504-11eb-8da4-85140cecad38.png">

**Comment by sarbajitdutta** [comment]
done
